server:
  port: 8090

requiredServices:
  ffmpeg: ${FFMPEG_PATH:C:/ffmpeg-master-latest-win64-gpl/bin/ffmpeg}
  ffprobe: ${FFPROBE_PATH:C:/ffmpeg-master-latest-win64-gpl/bin/ffprobe}

requiredParams:
  segmentDuration: ${SEGMENT_DEFAULT_DURATION:5}
  localTempPath: ${STORAGE_LOCAL_TEMP_PATH:C:/temp}
  readyIfSegmentCount: ${READY_IF_CREATED:3}
  serverUrl: ${URL:http://localhost:8090}
  maxSegmentsInPlaylist: ${MAX_SEGMENTS_IN_PLAYLIST:6}

storage:
  aws:
    enabled: true
    awsAccessKey: ${AWS_ACCESS_KEY:}
    awsSecretKey: ${AWS_SECRET_KEY:}
    awsBucket: ${AWS_BUCKET:}
  azure:
    enabled: false
    azureConnectionString: ${AZURE_CONNECTION_STRING:}
    azureContainer: ${AZURE_CONTAINER:}
  gcp:
    enabled: true
    gcpProjectId: ${GCP_PROJECT_ID:}
    gcpBucket: ${GCP_BUCKET:}


notification:
  enabled: false
  notifyBeforeMinutes:
    - "5"
    - "2"
    - "1"
    - "0"
  telegram:
    enabled: ${TELEGRAM_ENABLED:false}
    botToken: ${TELEGRAM_BOT_TOKEN:}
    chatIds:
      - ${TELEGRAM_CHAT_IDS:}
    template: "Stream URL: %s\nTime until start: %d minutes\nQuality: %s"

